// Code generated by MockGen. DO NOT EDIT.
// Source: api.go
//
// Generated by this command:
//
//	mockgen -source=api.go -destination=mock_repo.go -package=repo SLORepo
//

// Package repo is a generated GoMock package.
package repo

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSLORepo is a mock of SLORepo interface.
type MockSLORepo struct {
	ctrl     *gomock.Controller
	recorder *MockSLORepoMockRecorder
	isgomock struct{}
}

// MockSLORepoMockRecorder is the mock recorder for MockSLORepo.
type MockSLORepoMockRecorder struct {
	mock *MockSLORepo
}

// NewMockSLORepo creates a new mock instance.
func NewMockSLORepo(ctrl *gomock.Controller) *MockSLORepo {
	mock := &MockSLORepo{ctrl: ctrl}
	mock.recorder = &MockSLORepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSLORepo) EXPECT() *MockSLORepoMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSLORepo) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSLORepoMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSLORepo)(nil).Close), ctx)
}

// GetSLOByID mocks base method.
func (m *MockSLORepo) GetSLOByID(ctx context.Context, id string) (SLO, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSLOByID", ctx, id)
	ret0, _ := ret[0].(SLO)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSLOByID indicates an expected call of GetSLOByID.
func (mr *MockSLORepoMockRecorder) GetSLOByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSLOByID", reflect.TypeOf((*MockSLORepo)(nil).GetSLOByID), ctx, id)
}

// ListSLOs mocks base method.
func (m *MockSLORepo) ListSLOs(ctx context.Context) ([]SLO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSLOs", ctx)
	ret0, _ := ret[0].([]SLO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSLOs indicates an expected call of ListSLOs.
func (mr *MockSLORepoMockRecorder) ListSLOs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSLOs", reflect.TypeOf((*MockSLORepo)(nil).ListSLOs), ctx)
}

// ListSLOsByPromQLModule mocks base method.
func (m *MockSLORepo) ListSLOsByPromQLModule(ctx context.Context, serviceName string) ([]SLO, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSLOsByPromQLModule", ctx, serviceName)
	ret0, _ := ret[0].([]SLO)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSLOsByPromQLModule indicates an expected call of ListSLOsByPromQLModule.
func (mr *MockSLORepoMockRecorder) ListSLOsByPromQLModule(ctx, serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSLOsByPromQLModule", reflect.TypeOf((*MockSLORepo)(nil).ListSLOsByPromQLModule), ctx, serviceName)
}

// ListSLOsByPromQLService mocks base method.
func (m *MockSLORepo) ListSLOsByPromQLService(ctx context.Context, serviceName string) ([]SLO, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSLOsByPromQLService", ctx, serviceName)
	ret0, _ := ret[0].([]SLO)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSLOsByPromQLService indicates an expected call of ListSLOsByPromQLService.
func (mr *MockSLORepoMockRecorder) ListSLOsByPromQLService(ctx, serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSLOsByPromQLService", reflect.TypeOf((*MockSLORepo)(nil).ListSLOsByPromQLService), ctx, serviceName)
}

// Open mocks base method.
func (m *MockSLORepo) Open(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockSLORepoMockRecorder) Open(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockSLORepo)(nil).Open), ctx)
}

// SearchSLOs mocks base method.
func (m *MockSLORepo) SearchSLOs(ctx context.Context, category, keyword string) ([]SLO, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSLOs", ctx, category, keyword)
	ret0, _ := ret[0].([]SLO)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchSLOs indicates an expected call of SearchSLOs.
func (mr *MockSLORepoMockRecorder) SearchSLOs(ctx, category, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSLOs", reflect.TypeOf((*MockSLORepo)(nil).SearchSLOs), ctx, category, keyword)
}
